export const listItems = [
  {
    categoria: "Exercícios",
    itens: [
      {
        nome: "Membros Inferiores",
        itens: [
          { nome: "Leg Curl" },
          { nome: "Leg Extension" },
          { nome: "Agachamento Livre" },
          { nome: "Agachamento Sumô" },
          { nome: "Agachamento Búlgaro" },
          { nome: "Cadeira Abdutora" },
          { nome: "Cadeira Adutora" },
          { nome: "Avanço (Lunge)" },
          { nome: "Avanço Caminhando" },
          { nome: "Agachamento Hack" },
          { nome: "Passada com Halteres" },
          { nome: "Stiff com Halteres" },
          { nome: "Stiff com Barra" },
          { nome: "Ponte de Glúteo (Hip Thrust)" },
          { nome: "Hip Thrust Unilateral" },
          { nome: "Elevação de Panturrilha em Pé" },
          { nome: "Elevação de Panturrilha Sentado" },
          { nome: "Elevação de Panturrilha no Leg Press" },
          { nome: "Step Up com Halteres" },
          { nome: "Good Morning" },
          { nome: "Peso Morto Romeno" },
        ],
      },
      {
        nome: "Membros Superiores",
        itens: [
          {
            nome: "Peitoral",
            itens: [
              { nome: "Supino Reto com Halter" },
              { nome: "Supino Reto com Barra" },
              { nome: "Supino Inclinado com Halter" },
              { nome: "Supino Declinado" },
              { nome: "Crucifixo Inclinado" },
              { nome: "Crucifixo Declinado" },
              { nome: "Crossover no Cabo" },
              { nome: "Crucifixo no Banco Reto" },
              { nome: "Peck Deck" },
              { nome: "Flexões de Braço" },
              { nome: "Flexões Diamante" },
              { nome: "Flexões com Pés Elevados" },
              { nome: "Pullover com Halter" },
              { nome: "Dips entre Bancos" },
            ],
          },
          {
            nome: "Costas",
            itens: [
              { nome: "Puxada Frente" },
              { nome: "Puxada Frente Pegada Neutra" },
              { nome: "Remada Curvada" },
              { nome: "Remada Unilateral com Halter" },
              { nome: "Puxada Alta" },
              { nome: "Puxada Atrás" },
              { nome: "Remada Cavalinho (T-Bar Row)" },
              { nome: "Remada Sentado com Triângulo" },
              { nome: "Remada Serrote" },
              { nome: "Barra Fixa" },
              { nome: "Barra Fixa Pegada Neutra" },
              { nome: "Puxada no TRX" },
              { nome: "Face Pull" },
              { nome: "Pull Down com Corda" },
              { nome: "Remada na Máquina com Pegada Pronada" },
            ],
          },
          {
            nome: "Ombros",
            itens: [
              { nome: "Desenvolvimento com Halter" },
              { nome: "Elevação Lateral" },
              { nome: "Elevação Frontal" },
              { nome: "Desenvolvimento com Barra" },
              { nome: "Desenvolvimento Arnold" },
              { nome: "Crucifixo Inverso (Posterior de Ombro)" },
              { nome: "Elevação Lateral Inclinada" },
              { nome: "Encolhimento com Barra" },
              { nome: "Encolhimento com Halteres" },
              { nome: "Desenvolvimento Militar" },
              { nome: "Press Arnold" },
              { nome: "Elevação Lateral no Cabo" },
            ],
          },
          {
            nome: "Bíceps",
            itens: [
              { nome: "Rosca Direta com Barra" },
              { nome: "Rosca Alternada com Halteres" },
              { nome: "Rosca Martelo" },
              { nome: "Rosca Concentrada" },
              { nome: "Rosca Scott" },
              { nome: "Rosca Inversa" },
              { nome: "Rosca 21" },
              { nome: "Rosca no Cabo" },
              { nome: "Rosca Zottman" },
              { nome: "Rosca Spider" },
            ],
          },
          {
            nome: "Tríceps",
            itens: [
              { nome: "Tríceps Testa" },
              { nome: "Tríceps Pulley com Barra V" },
              { nome: "Tríceps Coice com Halter" },
              { nome: "Tríceps Banco" },
              { nome: "Tríceps Corda" },
              { nome: "Tríceps Francês" },
              { nome: "Mergulho em Paralelas" },
              { nome: "Kickback no Cabo" },
              { nome: "Extensão Overhead com Halter" },
              { nome: "Extensão Overhead com Corda" },
            ],
          },
          {
            nome: "Antebraço",
            itens: [
              { nome: "Rosca de Punho" },
              { nome: "Rosca de Punho Inversa" },
              { nome: "Extensão de Punho" },
              { nome: "Apertar Bola de Exercício" },
              { nome: "Segurar Halter por Tempo" },
              { nome: "Rotações de Punho com Halter" },
            ],
          },
        ],
      },
      {
        nome: "Core e Abdômen",
        itens: [
          { nome: "Prancha Frontal" },
          { nome: "Prancha Lateral" },
          { nome: "Abdominal Supra" },
          { nome: "Abdominal Infra" },
          { nome: "Abdominal Oblíquo" },
          { nome: "Russian Twist" },
          { nome: "Leg Raise" },
          { nome: "Hanging Knee Raise" },
          { nome: "Toe Touchers" },
          { nome: "Bicycle Crunch" },
          { nome: "V-Up" },
          { nome: "Dragon Flag" },
          { nome: "Abdominal com Roda" },
          { nome: "Abdominal na Polia Alta" },
          { nome: "Woodchopper" },
          { nome: "Superman" },
          { nome: "Hollow Hold" },
          { nome: "L-Sit" },
        ],
      },
      {
        nome: "Mobilidade e Aquecimento",
        itens: [
          { nome: "Mobilidade 90/90" },
          { nome: "Mobilidade com Elástico" },
          { nome: "Mobilidade com Bastão" },
          { nome: "Alongamento Dinâmico" },
          { nome: "Polichinelo" },
          { nome: "Corrida Estacionária" },
          { nome: "Skipping (Joelho Alto)" },
          { nome: "Jumping Lunges" },
          { nome: "Mobilidade de Tornozelo" },
          { nome: "Mobilidade de Coluna (Cat-Cow)" },
          { nome: "Mobilidade de Quadril (Pigeon Pose)" },
          { nome: "Alongamento de Peitoral na Porta" },
          { nome: "Rotação de Ombros com Bastão" },
          { nome: "Agachamento com Peso Corporal" },
          { nome: "Círculos com Braços" },
          { nome: "Twist Russo sem Peso" },
          { nome: "Alongamento de Isquiotibiais em Pé" },
          { nome: "Alongamento de Quadríceps" },
        ],
      },
      {
        nome: "Cardio",
        itens: [
          { nome: "Esteira" },
          { nome: "Transport" },
          { nome: "Bicicleta Ergométrica" },
          { nome: "Escada" },
          { nome: "Remo" },
          { nome: "Elliptical" },
          { nome: "Skipping Rope (Pular Corda)" },
          { nome: "Burpee" },
          { nome: "Jumping Jack" },
          { nome: "High Knees" },
          { nome: "Butt Kicks" },
          { nome: "Box Jump" },
          { nome: "Shuttle Run" },
          { nome: "Battle Ropes" },
          { nome: "Sled Push" },
        ],
      },
    ],
  },
  {
    categoria: "Grupos Musculares",
    itens: [
      {
        nome: "Membros Inferiores",
        itens: [
          { nome: "Quadríceps" },
          { nome: "Isquiotibiais" },
          { nome: "Glúteos" },
          { nome: "Adutores" },
          { nome: "Abdutores" },
          { nome: "Panturrilhas" },
          { nome: "Sóleo" },
          { nome: "Gastrocnêmio" },
          { nome: "Tensor da Fáscia Lata" },
          { nome: "Psoas" },
          { nome: "Sartório" },
        ],
      },
      {
        nome: "Membros Superiores",
        itens: [
          { nome: "Peitoral Maior" },
          { nome: "Peitoral Menor" },
          { nome: "Dorsal / Latíssimo" },
          { nome: "Trapézio" },
          { nome: "Ombros / Deltoides" },
          { nome: "Deltóide Anterior" },
          { nome: "Deltóide Lateral" },
          { nome: "Deltóide Posterior" },
          { nome: "Bíceps Braquial" },
          { nome: "Tríceps Braquial" },
          { nome: "Antebraço" },
          { nome: "Flexores do Punho" },
          { nome: "Extensores do Punho" },
          { nome: "Supinadores" },
          { nome: "Pronadores" },
          { nome: "Serrátil Anterior" },
          { nome: "Romboides" },
        ],
      },
      {
        nome: "Core",
        itens: [
          { nome: "Reto Abdominal" },
          { nome: "Oblíquos Externos" },
          { nome: "Oblíquos Internos" },
          { nome: "Lombar" },
          { nome: "Transverso do Abdômen" },
          { nome: "Multífidos" },
          { nome: "Eretores da Espinha" },
          { nome: "Quadrado Lombar" },
          { nome: "Diafragma" },
        ],
      },
    ],
  },
  {
    categoria: "Aparelhos",
    itens: [
      {
        nome: "Puxadas e Remadas",
        itens: [
          { nome: "Low Row" },
          { nome: "Row Pure" },
          { nome: "Cross Over" },
          { nome: "D.A.P (Dual Adjustable Pulley)" },
          { nome: "Remada Sentada no Cabo" },
          { nome: "Puxador Frontal com Triângulo" },
          { nome: "Remada Alta Máquina" },
          { nome: "Remada Baixa Máquina" },
          { nome: "Pull Down Máquina" },
          { nome: "Lat Pulldown Máquina" },
          { nome: "Reverse Grip Lat Pulldown" },
          { nome: "Close Grip Lat Pulldown" },
        ],
      },
      {
        nome: "Peitoral e Ombros",
        itens: [
          { nome: "Supino Máquina" },
          { nome: "Shoulder Press Pure" },
          { nome: "Peck Deck (Voador)" },
          { nome: "Crossover Máquina" },
          { nome: "Crucifixo Inverso na Máquina" },
          { nome: "Incline Press Máquina" },
          { nome: "Decline Press Máquina" },
          { nome: "Shoulder Press Máquina" },
          { nome: "Lateral Raise Máquina" },
          { nome: "Rear Delt Máquina" },
        ],
      },
      {
        nome: "Pernas",
        itens: [
          { nome: "Cadeira Extensora" },
          { nome: "Mesa Flexora" },
          { nome: "Leg Press" },
          { nome: "Leg Press 45°" },
          { nome: "Hack Squat" },
          { nome: "Banco Abdutor" },
          { nome: "Banco Adutor" },
          { nome: "Glute Kickback Máquina" },
          { nome: "Panturrilha Máquina Sentado" },
          { nome: "Panturrilha Máquina em Pé" },
          { nome: "Panturrilha no Leg Press" },
          { nome: "Smith Machine" },
          { nome: "GHD (Glute Ham Developer)" },
          { nome: "Hip Abductor Máquina" },
          { nome: "Hip Adductor Máquina" },
          { nome: "Seated Leg Curl" },
          { nome: "Standing Leg Curl" },
        ],
      },
      {
        nome: "Core e Funcionais",
        itens: [
          { nome: "Banco de Abdominais" },
          { nome: "Banco Romano (Lombar)" },
          { nome: "Kinesis" },
          { nome: "Prancha no Bosu" },
          { nome: "Ab Roller (Roda Abdominal)" },
          { nome: "Medicine Ball para Abdominais" },
          { nome: "TRX para Core" },
          { nome: "Captain's Chair" },
          { nome: "Back Extension Máquina" },
          { nome: "Rotational Torso Máquina" },
          { nome: "Abdominal Máquina" },
          { nome: "Hyperextension Bench" },
        ],
      },
      {
        nome: "Cardio",
        itens: [
          { nome: "Esteira" },
          { nome: "Transport" },
          { nome: "Bicicleta Ergométrica" },
          { nome: "Escada" },
          { nome: "Remo" },
          { nome: "Elliptical" },
          { nome: "StairMaster" },
          { nome: "VersaClimber" },
          { nome: "Air Bike" },
          { nome: "SkiErg" },
        ],
      },
      {
        nome: "Acessórios",
        itens: [
          { nome: "Bancos de Supino" },
          { nome: "Bancos de Halteres" },
          { nome: "Barras Olímpicas" },
          { nome: "Halteres" },
          { nome: "Kettlebells" },
          { nome: "Barras Paralelas" },
          { nome: "Barras Fixas" },
          { nome: "Plataformas de Salto" },
          { nome: "Caixas de Pliometria" },
          { nome: "Bolas Suíças" },
          { nome: "Rolos de Abdominal" },
          { nome: "Cintos de Levantamento" },
          { nome: "Luvas de Treino" },
          { nome: "Faixas Elásticas" },
          { nome: "Anilhas" },
        ],
      },
    ],
  },
  {
    categoria: "Funcionais e Calistênicos",
    itens: [
      { nome: "Burpee" },
      { nome: "Prancha" },
      { nome: "Mountain Climbers" },
      { nome: "Agachamento com Peso Corporal" },
      { nome: "Flexão de Braço" },
      { nome: "Barra Fixa" },
      { nome: "Pistol Squat" },
      { nome: "Wall Sit" },
      { nome: "Muscle Up" },
      { nome: "Handstand Push Up" },
      { nome: "Front Lever" },
      { nome: "Back Lever" },
      { nome: "Planche" },
      { nome: "Human Flag" },
      { nome: "L-Sit" },
      { nome: "Dips" },
      { nome: "Push Up com Bola Medicinal" },
      { nome: "Pull Up" },
      { nome: "Chin Up" },
      { nome: "Box Jump" },
      { nome: "Clapping Push Up" },
      { nome: "Archer Push Up" },
      { nome: "One Arm Push Up" },
      { nome: "Handstand Hold" },
      { nome: "Ring Dips" },
      { nome: "Ring Rows" },
      { nome: "Ring Push Ups" },
      { nome: "Dragon Walk" },
      { nome: "Bear Crawl" },
    ],
  },
  {
    categoria: "Treinos Específicos",
    itens: [
      {
        nome: "HIIT",
        itens: [
          { nome: "Tabata" },
          { nome: "AMRAP" },
          { nome: "EMOM" },
          { nome: "Circuit Training" },
          { nome: "Intervalado 1:1" },
          { nome: "Intervalado 2:1" },
        ],
      },
      {
        nome: "CrossFit",
        itens: [
          { nome: "Fran" },
          { nome: "Cindy" },
          { nome: "Murph" },
          { nome: "Grace" },
          { nome: "Isabel" },
          { nome: "Annie" },
          { nome: "Karen" },
          { nome: "Helen" },
        ],
      },
      {
        nome: "Powerlifting",
        itens: [
          { nome: "Agachamento" },
          { nome: "Supino" },
          { nome: "Levantamento Terra" },
          { nome: "Good Morning" },
          { nome: "Box Squat" },
          { nome: "Pause Bench Press" },
          { nome: "Deficit Deadlift" },
        ],
      },
      {
        nome: "Mobilidade e Flexibilidade",
        itens: [
          { nome: "Yoga" },
          { nome: "Pilates" },
          { nome: "Alongamento Estático" },
          { nome: "Foam Rolling" },
          { nome: "Mobilidade de Tornozelo" },
          { nome: "Mobilidade de Quadril" },
          { nome: "Mobilidade Torácica" },
        ],
      },
      {
        nome: "Treino em Casa",
        itens: [
          { nome: "Treino com Peso Corporal" },
          { nome: "Treino com Faixas Elásticas" },
          { nome: "Treino com Halteres" },
          { nome: "Treino com Kettlebell" },
          { nome: "Treino com Bola Suíça" },
          { nome: "Treino Suspenso (TRX)" },
        ],
      },
    ],
  },
];
export const flattenList = (items, path = []) => {
  return items.flatMap((item) => {
    const currentPath = [...path, item.nome || item.categoria];
    if (item.itens) {
      return flattenList(item.itens, currentPath);
    } else {
      return {
        label: item.nome,
        value: `/dashboard/${slugify(
          currentPath[currentPath.length - 2]
        )}/${slugify(item.nome)}`,
        categoria: currentPath[currentPath.length - 2],
      };
    }
  });
};

const slugify = (str) =>
  str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, "-")
    .replace(/[^\w\-]+/g, "")
    .replace(/\-\-+/g, "-")
    .trim();
